### ISSUE TITLE
Testing context

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#33]
Why trying to test for #30 , I have problem writing test:

- How to test with two context? I tried to duplicate `context` in `conftest.py` but it seems to invoke a segmentation fault.
- Should a context only be used within a `with` block? The contexts seem to enter before the `with`.

`src/palace.pyx`
```python
def __enter__(self) -> Context:
    use_context(self)
    Context.current_contexts.append(self)
    return self
```

`tests/conftest.py`
```python
def test_with_context(context):
    current = current_context()  # module level, imported from palace
    assert current is None  # fail - pass if assert current is context
    with context:  # segmentation fault
        assert current is context
```

I thought that `__enter__` is called after `with` so there should be no context before it.

**Comment by McSinyx** [comment]
I will address the issues with the code (not necessarily yours) first, then move on to the explanation.

To begin with, don't cache all previous contexts (not mentioning `current_contexts` is a very misleading name for the purpose), just the the one that was current when `__enter__` is enough.  And that should not anyhow be exposed as part of the API (use `cdef` **without** `public`/`readonly` if you're going with Cython attribute, otherwise prepend the name with an underscore.).

Don't use a context fixture (look it up in pytest doc if you haven't) when we need to test the setup/teardown of it.  Yes, the source tests are ill-formed, they should only use context and device fixtures, not source (and then there'll be no need to revert each property to there initial state), but that's out of the scope of #31.

`conftest.py` is a pytest thing that expose all content to all neighbors test modules, don't put tests in there, it does not make sense.

Now, about the context manager, or the `with` thing as you mentioned, what happens behind the scene is, e.g. with
```python
class Foo:
    def __enter__(self): return 42
    def __exit__(self, *exc): exit()
```
(aight I know it does not make any sense) we run
```python
with Foo() as foo: print(foo)
print(69)
```
what you'll get is a single line with number `42`.  This is because the `as` thing give you what ever `__enter__` returns, and in our case (palace) it happens to be the exact same object.  Whatever happens within the with block, `__exit__` in warrantied to be executed not after the next statement (`print(69)`).

Now back to your test, when you invoke the `context` fixture, which is basically `yield`ed from within a context manager (yes `yield` is capable of performing some black magic so pytest can postpone the inner block from finishing/`__exit__` from destroying the context, see dabeaz lectures on this, they're mind blowing), so my guess would be `current_context` returns a context equals to `context`.  I've no idea why calling `__enter__` twice would gives a segfault (looking up Python doc or asking on freenode might help, just too lazy to do it now), but that never happens in practical use so we'll be fine.

When I mentioned about the test for #30, I meant something that make sure the sample code would behave as expected.  I hope the test you showed me is not the final version.

**Comment by Huy-Ngo** [comment]
> don't cache all previous contexts (not mentioning `current_contexts` is a very misleading name for the purpose), just the the one that was current when `__enter__` is enough.

Ah, so like a linked list?

>  I hope the test you showed me is not the final version.

Of course not. It's just to show my points.

**Comment by McSinyx** [comment]
> Ah, so like a linked list?

No, just the current one.

**Comment by Huy-Ngo** [comment]
I mean each context has a property pointing to the previous context, something like

```
first_context.previous = None
second_context.previous = first_context
third_context.previous = second_context
```
which looks kinda like a linked list to me.

I've looked at `alure::getCurrent` source code:

```cpp
class ContextImpl {
    static ContextImpl *sCurrentCtx;
    static thread_local ContextImpl *sThreadCurrentCtx;

public:
    static void MakeCurrent(ContextImpl *context);
    static ContextImpl *GetCurrent()
    {
        auto thrd_ctx = sThreadCurrentCtx;
        return thrd_ctx ? thrd_ctx : sCurrentCtx;
    }

    static void MakeThreadCurrent(ContextImpl *context);
    static ContextImpl *GetThreadCurrent() { return sThreadCurrentCtx; }
...
```
I have no idea what `sCurrentCtx` and `sThreadCurrentCtx` are, because it's not used anywhere else. Either way, it's not returning a null pointer and I can't think of a way to know if there's a context being used.

**Comment by Huy-Ngo** [comment]
I'll close this issue since it can be tested now. Let's direct implementation issues to #31 or #30
