### ISSUE TITLE
Context returned from current_context has wrong message handler

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#41]
The function `current_context` implemented by #31 gives you the context that is used currently by creating a new context then copy its properties. However, the message handler isn't copied to at all.

```python
with context:
    current = current_context()
    assert current.message_handler is context.message_handler  # fail
```

**Comment by McSinyx** [comment]
Please elaborate, i.e. what causes this?

**Comment by Huy-Ngo** [comment]
Do we actually need `current.message_handler is context.message_handler` or  just `current.message_handler == context.message_handler` (as for other properties?)

In the `Context` class:

```python
cdef class Context:
...
    def __init__(self, device: Device, attrs: Dict[int, int] = {}) -> None:
        ...
        self.message_handler = MessageHandler()
        self.impl.set_message_handler(
            shared_ptr[alure.MessageHandler](new CppMessageHandler(self)))
```

I'm not sure why this doesn't work. Maybe we should refer to alure source code as well?

**Comment by McSinyx** [comment]
The palace message handler is accessed by the alure one via the parent palace context: https://github.com/McSinyx/palace/blob/cb2e2eac407c934710069fcfbee1b3efd91ccd8b/src/palace.pyx#L1817-L1844

`current_context` return a new palace context, and thus its palace message handler isn't connected to the set alure one.  The fix would involve letting `CppMessageHandler` keeping a reference to `MessageHandler` instead of `Context` I think, do you want to work on this?
