### ISSUE TITLE
How to document enum values for users?

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#47]
While trying to do the TODO's in `Context`, I have to implement the `DistanceModel`:

https://github.com/McSinyx/palace/blob/1f482e3676ed82b5329612e9c1c64b6e0bfbe9ee/src/alure.pxd#L111-L118

Looking for similar examples, it leads me to another enum class:

https://github.com/McSinyx/palace/blob/16bdb47c5a1a805dcd9a2a4178e13521c0a70c96/src/palace.pyx#L1994-L2014

... which has a lot of values as well, and I wonder how the users could know which options are available?

**Comment by McSinyx** [comment]
For chanel configurations, there is `channel_configs` which is a set of valid values.  While it works, it's much slower than using enumerants (int vs str comparison).  Feel free to experiment with Python [Enum](https://docs.python.org/3/library/enum.html) and keep this issue open until we come to a conclusion.  I have never tried it, it could be more intuitive than the string thing.

**Comment by Huy-Ngo** [comment]
Wait... Do we need to change the name of `None`, since it's a keyword in Python?

**Comment by McSinyx** [comment]
Can it compile though?  However I suggest to avoid using the name even if it does since it will cause confusion later on.

**Comment by Huy-Ngo** [comment]
Currently it doesn't compile, due to another code (available resamplers). Somehow it can't convert ArrayView to vector.

**Comment by McSinyx** [comment]
See [this](https://github.com/McSinyx/palace/blob/master/src/bases.h#L108-L110) for an example, which I think is not really difficult to perform in Cython.

**Comment by Huy-Ngo** [comment]
I remain confused. But this belongs to another part so let me elaborate in another issue: #49.

**Comment by Huy-Ngo** [comment]
I've been toying around with `enum.Enum` and come into a problem:
- If I define it as a `class`, its values can't be `cdef`'ed and therefore I can't assign alure's values to them.
- If I define it as a `cdef class`, it's a C++ class and therefore can't inherit `enum.Enum`.

So my current solution is to define an enum class with `int` value and implement a converter like `to_channel_config` but with input as int instead. Does that sound good?

Also using `enum.Enum` allows me to do something like:

```python
cdef alure.DistanceModel to_distance_model(int model_id) except + : 
    cdef models = [
        alure.DistanceModel.No,
        alure.DistanceModel.InverseClamped,
        alure.DistanceModel.LinearClamped,
        ...
    ]
    return models[model_id]
```

... which is shorter and pleasant to write than a chain of elif, imo.

**Comment by McSinyx** [comment]
That sounds great, however I'm not sure I understand you correctly.  Please push your (draft is OK, but should be working) patch to a branch so I can see it clearer.

**Comment by Huy-Ngo** [comment]
It's not running yet, [log here](https://gist.github.com/Huy-Ngo/fd995f9ebdff81bf8e4411dc32160206). Since it has some `is_unsigned` in the log I tried to use `unsigned` instead of `int`, but it resulted in the same error.

**Comment by McSinyx** [comment]
The compile error looks like Cython's fault of generating C++ source.  I'm not exactly sure why but you can try to read the C++ output (palace.cpp) around the line that causes the error and try to figure out.  There's a Cython option to disable bound checking or something like that IIRC.

**Comment by Huy-Ngo** [comment]
I know nothing more when I read the cpp code: It tries to apply some arithmetic/logical operations on `enum alure::DistanceModel`, which is not defined if I'm not wrong. If I use if/else chain though, the build is successful.

**Comment by McSinyx** [comment]
I took a look at the output C++ and figured that the C++ enum is not treated as enum/integral by Cython, so maybe that's why it doesn't work.  You might want to contact upstream for a proper explanation (remember that tight communication with upstream is a very important part of free software development).

BTW it was a mistake to use PascalCase for enumerants.  As part of solving this issue, could you please also change existing enums *values* to use UPPER_CASE?

Additionally I saw you use `tox` for iterative compilation.  While it works (and probably the safest), running `setup.py` directly would save you the time setting up (and tearing down) venvs, moreover `tox` compiles with CYTHON_TRACE on, which is a bit slower in my experience.

**Comment by Huy-Ngo** [comment]
For upstream I should ask in [mail group](https://groups.google.com/forum/#!forum/cython-users) right? Do I just join and post it like a GH issue?

BTW if this Enum thing is successful should we convert the currently existing enums to be consistent?

**Comment by McSinyx** [comment]
> For upstream I should ask in mail group right? Do I just join and post it like a GH issue?

It doesn't matter.  The mail group is a bit more active I think.

> BTW if this Enum thing is successful should we convert the currently existing enums to be consistent?

I'm not sure if that's a good idea.  The one for spatialize should be kept as-is because `Optional[bool]` is more intuitive than a custom type.  The ones for device names are handled internally by palace.  The only concern is enums for sample types and channel configurations, which for now I'd recommend keeping it that way until there is a performance issue.  The (internal) enum names tho, should be changed for consistency.
