### ISSUE TITLE
Wrapping alure::ArrayView<> template

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#49]
Currently I'm working on `getAvailableResamplers` and some buffers functions in `Context`, both of which use `ArrayView<String>`.

It says I there is [no known conversion](https://gist.github.com/Huy-Ngo/9cb810eedeb4a7328aea2406dce0e353#file-err_available_resamplers-L40-L45) from `ArrayView<String>` to `vector[string]`. I'm confused, as other `ArrayView` variables can be converted to `vector` without problem (e.g. `ArrayView<Source>`).

@McSinyx suggested, one can do [this](https://github.com/McSinyx/palace/blob/master/src/bases.h#L108-L110) but I stay unclear about what I should do. I suppose it's copying the array manually by `std::copy` but I don't know how to do that in `alure.pxd`.

**Comment by McSinyx** [comment]
> I'm confused, as other `ArrayView` variables can be converted to vector without problem (e.g. `ArrayView<Source>`).

I don't think so, at least not magically.  I think you were referring to `Vector<Source>`.

There are two options I can think of:
1. Use `std::copy`.  It works, but it's stupid, since the copied vector will be disposed right away.  All you need is to `cimport copy` from `libcpp.algorithm` and write the exact same thing I did in C++, plus expose needed `alure::ArrayView` methods.
2. Be lazy.  Cython provide `iterator` bridge for C++ objects, so you can `cdef` the returned value (say `resamplers`) from alure API then `return [resampler for resampler in resamplers]`.  You'll need to expose the `iterator` attributes of `alure::ArrayView` for this to work I think.

I wonder if you have the reverse (e.g. `precacheBuffersAsync(ArrayView<StringView> names)`) working alright, if not, then a hint would be to take a look at `alure2-typeviews.h`, where you'll see constructors of these views can take C++ std stuff in implicitly, hence the easy handling of `ArrayView<AttributePair>`.

**Comment by McSinyx** [comment]
Does any of the mentioned approach work for you?

**Comment by Huy-Ngo** [comment]
Sorry I haven't touched it lately because of philosophy report assignment at school.

**Comment by Huy-Ngo** [comment]
Anyway using `ArrayView<String>` in `alure.pxd` seems to make the thing collapse, but I haven't recorded that yet.

**Comment by Huy-Ngo** [comment]
Okay so here is where I'm stuck at:

Since the functions declared in `alure.pxd` is header-like and so I can't just write their bodies there, so I don't know how to put a converting mechanism there. It also doesn't recognize `alure::ArrayView<String>` if I set it as return type, and if I try to do that, it makes all the enum classes broken.

**Comment by McSinyx** [comment]
Alright (although I haven't touched the philosophy assignment lmao), `String` is actually defined in `alure`, but instead of writing `alure::String`, just use `string` and let implicit conversion does it job.

> it makes all the enum classes broken.

If the above doesn't fix this, please post to error so I may help investigate.

For the conversion utils, for now just put them at the bottom of the pyx file.  Ideally they should be in there own file (e.g. `helpers.pyx` and declared in `helpers.pxd`), but that can be done later (I'm not sure how to compile that properly, feel free to experiment).

**Comment by Huy-Ngo** [comment]
> although I haven't touched the philosophy assignment lmao

Wot dude the due is tomorrow

> String is actually defined in alure, but instead of writing alure::String, just use string and let implicit conversion does it job.

Oh wait, I was confusing with Java and thought `String` should be capitalized. Either way, I've tried with both cases, with and without quotes (`'alure::ArrayView<string> get_available_resamplers'`), and with `<>` replaced with `[]`. All of them lead to enum classes broken (maybe relates more to syntactic error).

> For the conversion utils, for now just put them at the bottom of the pyx file.

Ok I get the idea. Somehow I thought it should be in the pxd file.

> If the above doesn't fix this, please post to error so I may help investigate.

Hmm... post the code that make the error or just the error log? (Sounds weird but I was actually thinking of doing that)

**Comment by McSinyx** [comment]
> Wot dude the due is tomorrow

I though it is [The Day After Tomorrow](https://en.wikipedia.org/wiki/The_Day_After_Tomorrow):

> Submission in person will be from 12h30 to 13h30, 18/3 at [...]

>  All of them lead to enum classes broken (maybe relates more to syntactic error).

Glad you figured it out.

> Hmm... post the code that make the error or just the error log?

While it's not needed this time, I meant the log, since you can always push the latest local here.  And naturally I'm too lazy to fetch and run locally (Travis is terribly slow lately).

**Comment by Huy-Ngo** [comment]
[All in one](https://gist.github.com/Huy-Ngo/53396e60ac145e0437220f462ebc2acf)

The last one seems the sanest, I may need to import alure... how?

As for why I tried those insane attempts, it's because I was suggested

> `ArrayView<string> ...` should do

(I've also tried [`ArrayView<string>`](https://gist.github.com/Huy-Ngo/f270c28c456f042c2fbcbc3abe7db681), forgot to add it)

**Comment by McSinyx** [comment]
Currently in `alure.pxd`, this is obviously wrong (my fault), since `alure::ArrayView` cannot be implicitly converted to `std::vector`:

    vector[string] get_available_resamplers 'getAvailableResamplers'() except +

You'll need to declare `alure::ArrayView` in this file so it can compile though, thus it'd be something like:

    ArrayView[string] get_available_resamplers 'getAvailableResamplers'() except +

Just like every other classes in alure namespace, `alure::ArrayView` should be `cdef extern from 'alure2-...` (I forgot where that is, just grep it up).  Not sure if this is enough.  Also in the pyx file the alure stuff are conveniently in `alure` name space already, so access it with `alure.ArrayView` while writing the helper.

**Comment by Huy-Ngo** [comment]
So it would be:

```
# Helper classes ## Hmm I guess not, because that's from somewhere else
cdef extern from 'alure2-...' namespace 'alure' nogil:
    cdef ArrayView 'alure::ArrayView'
...
```

... correct?

**Comment by McSinyx** [comment]
```cython
cdef cppclass ArrayView:
    [put necessary methods here]
```

Edit: the extern thing should be on the module-level scope.

**Comment by Huy-Ngo** [comment]
I can't just `ctypedef` it? So I have to see the source code to see which functions it has?

**Comment by Huy-Ngo** [comment]
Also since it's a template in C++, it has a variable for datatype, how do I get it in cython?

**Comment by McSinyx** [comment]
> I can't just ctypedef it? So I have to see the source code to see which functions it has?

That's on going development I think (not sure search Cython issues), but normally you have to expose the methods you need.

Also `ctypedef` is for type aliases (i.e. the original header either use `typedef` or `using`), if no method needed just use `pass` in the place.

> Also since it's a template in C++, it has a variable for datatype, how do I get it in cython?

See Cython doc (the using C++ ... thing), in short use square brackets.

**Comment by McSinyx** [comment]
BTW your branch started out great but now the changes are a bit fragmented.  So remember to rearrange changes in logical commits (they touches many places so squashing them all together won't do).

**Comment by Huy-Ngo** [comment]
Ok, got it

**Comment by Huy-Ngo** [comment]
Resolved via 692f3d7

**Comment by McSinyx** [comment]
Does `Context.available_resamplers` work now?

**Comment by Huy-Ngo** [comment]
I was optimistic that it would, but it doesn't, and it says `incompatible types for begin() and end()` here in the line `[resampler for resampler in resamplers]`. Shouldn't they both be of type `string*`?

**Comment by McSinyx** [comment]
I hope the issue is with that `begin` and `end` are defined as `const_iterator` (which is inherently the same type).  Otherwise, ask upstream (I don't see this documented anywhere, but I believe that there's a way to make it work).

**Comment by Huy-Ngo** [comment]
Apparently it doesn't fix that. I implemented `const_iterator` as well as `cbegin()` and `cend()` and it still gives the [same error](https://gist.github.com/Huy-Ngo/0f1a0ba26766414a64b06314894a7586).

By asking upstream you mean ask in a new issue in alure?

**Comment by McSinyx** [comment]
I mean the upstream that can answer this sort of question evolving the requirements for a C++ container to be used as a Python iterable.  While this is definitely a documentation issue (lacking), I've heard that the [mail list](https://groups.google.com/forum/#!forum/cython-users) is more active.

**Comment by McSinyx** [comment]
I took a look at your current implementation and found this
```cython
cdef extern from 'alure2-typeviews.h' namespace 'alure' nogil:
    cdef cppclass ArrayView[T]:
        ctypedef T value_type

        ctypedef const value_type* const_iterator
```

My (hopefully) educated guess would be somehow Cython mess up type aliases (yes, I'm aware that the last line is duplicated, but without it the problem persists) instead of reporting error of some kind.  BTW in Cython, you can drop these unnecessary aliases and go straight for
```cython
const T* begin() except +
const T* end() except +
```

The reason for this is extern declaration is purely for call interfacing, i.e. so Cython knows which type, aliased or not, of the arguments and return value routine is taking/giving.  Furthermore, try to minimize the methods externed, since it, as explained, does nothing useful but redeclared the exactly declared stuff.  For `alure::ArrayView`, I think just the null constructor (for auto deallocation) and `begin`-`end` is enough.

For now please file some issues on Cython tracker asking for documentation on C++ iterator (and probably a PR too), as well as the parsing bug, since we're no longer in the matter of urgency.

**Comment by Huy-Ngo** [comment]
Oh, that did solve the problem. I tried to add those alias because I thought the problem was not using it, turns out I forgot to use const.

**Comment by Huy-Ngo** [comment]
Close via 400fa77

**Comment by McSinyx** [comment]
Please consider open a PR ASAP to avoid integration hell (which might already be a problem).

**Comment by Huy-Ngo** [comment]
Let me mark undone jobs with TODO's first. 

Oh wait, there's nothing to mark as far as I'm aware.
