### ISSUE TITLE
Using Twine to upload to PyPI

### ISSUE THREAD

**Issue by 9a24f0** [McSinyx/palace#74]
I tried to look at Twine's guide as in [here](https://pypi.org/project/twine/)
However, I got this when using `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`

```
HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for details for url: https://test.pypi.org/legacy/
```

**Comment by 9a24f0** [comment]
@McSinyx any guide on this :/

**Comment by McSinyx** [comment]
Could be invalid or non-existent authentication information.  What username/password did you use?  BTW please be explicit, `dist/*` is not.

**Comment by McSinyx** [comment]
BTW you can benefit from having something like [this](https://github.com/McSinyx/dotfiles/blob/master/dev/.pypirc) at `$HOME`.

**Comment by 9a24f0** [comment]
oops, please check if I have done it correctly...
Palace is on 0.1.12 now on PyPI

**Comment by McSinyx** [comment]
You need to do the other things said in GH-70 to create the wheels.

**Comment by McSinyx** [comment]
Oh f\*k I told you to be explicit on the uploading, we don't want eggs there.

**Comment by McSinyx** [comment]
Jesus you uploaded all the eggs there ugh.

**Comment by 9a24f0** [comment]
the eggs?...

**Comment by McSinyx** [comment]
NEVER USE WILDCARDS FOR ANYTHING THAT IS IMPORTANT, NAMELY VERSION CONTROL, RELEASES, ETC!  THIS IS NOT EVEN THE FIRST TIME I HAVE TO TELL YOU THIS!  Only upload the sdist (source distribution)!

**Comment by 9a24f0** [comment]
How can I fix it then.

**Comment by McSinyx** [comment]
Already deleted ugh, just always be extra careful when do things that are important.  Now please draft the release on GitHub so Travis can publish the wheels.

**Comment by McSinyx** [comment]
Labeled as invalid because the issue is with usage of Twine, which is out of palace's scope.

**Comment by McSinyx** [comment]
Labeled as distribution since it might fit better.

@9a24f0 and @Huy-Ngo, after the discussion linked above, I realized a few things:
1. Sometimes seemingly I pushed you guys too hard outta your comfort zones, and when things went weird I freaked tf out and was not really nice.  Please take my apologies for any unpleasant moment you might experienced in the past.  Additionally, if there's anything wrong with the way I manage this project, it's time to tell my now so we can fix it together.
2. As a reminder, `pip install . -v --no-build-isolation` might be a decent alternative to `./setup.py install --user` if you like the output.

Thank you for the (past, present and future) time and effort you all put into this and also with me :smile:  Cheers!
